@extends('layouts.sales')
@section('content')

<div class="">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading text-center">
				Enquiry Data (Generated By You)
			</div>
			<div class="panel-body" style="overflow-x: auto">
				<table border="1" id="myTable" class="table table-responsive table-striped table-hover">
					<thead>
						<tr>
							
							<th style="text-align: center">Ward Name</th>
							<th style="text-align: center">Name</th>
							<th style="text-align: center">Requirement Date</th>
							<th style="text-align: center">Enquiry Date</th>
							<th style="text-align: center">Contact</th>
							<th style="text-align: center">Product</th>
							<th style="text-align: center">Quantity</th>
							<th style="text-align: center">Status</th>
							<th style="text-align: center">Remarks</th>
							<th style="text-align: center">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($pipelines as $enquiry)
						<tr>
							
							<td style="text-align: center">
								{{$subwards2[$enquiry->project_id]}}
							</td>
							<td style="text-align: center">
								{{$enquiry -> procurement_name}}
							</td>
							<td style="text-align: center">
								{{$newDate = date('d/m/Y', strtotime($enquiry->requirement_date)) }}
							</td>
							<td style="text-align: center">
								{{ date('d/m/Y', strtotime($enquiry->created_at)) }}
							</td>
							<td style="text-align: center">
								{{$enquiry -> procurement_contact_no }}
							</td>
							<td style="text-align: center">
								{{$enquiry -> main_category}} ({{ $enquiry->sub_category }}), {{ $enquiry->material_spec }}
							</td>
							<td style="text-align: center">
								{{$enquiry -> quantity}}
							</td>
							<td style="text-align: center">
								{{ $enquiry->status}}
							</td>
							<td style="text-align: center" onclick="edit('{{ $enquiry->id }}')" id="{{ $enquiry->id }}">
								{{ $enquiry->notes }}
							</td>
							<td style="text-align: center" >
								<a href="{{ URL::to('/') }}/editenq?reqId={{ $enquiry->id }}" class="btn btn-warning btn-sm pull-right">Edit</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
			<div class="panel-footer">
				{{ $pipelines->links() }}
			</div>
		</div>
	</div>
</div>
@endsection
