@extends('layouts.app')
@section('content')
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" />

  <style>
input[data-readonly] {
  pointer-events: none;
}
</style>
  <style>
* {box-sizing: border-box}
/* Style the tab */
.tab {
    float: left;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
    width: 30%;
    height: 300px;
}

/* Style the buttons inside the tab */
.tab button {
    display: block;
    background-color: inherit;
    color: black;
    padding: 22px 16px;
    width: 100%;
    border: none;
    outline: none;
    text-align: left;
    cursor: pointer;
    font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current "tab button" class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    float: left;
    padding: 0px 12px;
    border: 1px solid #ccc;
    width: 70%;
    border-left: none;
    height: 300px;
    display: none;
}

/* Clear floats after the tab */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}
</style>
<script>
function openCitytest(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>
</head>
<body>

<div class="col-md-12">
    <div class="panel panel-primary" style="overflow-x: scroll;">
        <div class="panel-heading text-center" style="width:98%;position:absolute;">
            <b style="color:white;font-size:1.4em">Orders</b>
           <button type="button" onclick="history.back(-1)" class="btn btn-default pull-right" style="margin-top:-3px;" > <i class="fa fa-arrow-circle-left" style="width:30px;"></i></button>
            <h4 class="pull-left" style="margin-top: -0.5px;">Total Count : {{ $view->total() }}</h4>

        </div><br><br>
        <div id="myordertable" class="panel-body">
            <form action="orders" method="get">
                <div class="input-group col-md-3 pull-right">
                    <input type="text" class="form-control pull-left" placeholder="Enter project id" name="projectId" id="projectId">
                    
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-success">Search</button>
                    </div>
                </div>
            </form>
             
            <br><br>
            <table class="table table-responsive table-striped" border="1">
                <thead>
                    <tr>

                        <th>Project ID</th>
                        <th>Enquiry ID</th>
                        <th>Order Id</th>
                        <th>Generated By</th>
                        <th>Required</th>
                        <th>Quantity</th>
                        <th>Assign Logistics</th>
                        <th>Requirement Date</th>
                        <th>Payment Status</th>
                        <th>Payment Mode</th>
                        <th>LPO</th>
                       <!--  <th>Delivery Status</th> -->
                        <!-- <th>Print Invoice</th> -->
                        <th> Confirm Order </th>
                       
                        <th>Get Purchase Order</th>
                        <th>Supplier Invoice</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($view as $rec)
                    <tr style="{{ $rec->order_status == 'Order Cancelled' ? 'background-color: #ffbaba;' : '' }}" id="row-{{$rec->id}}">
                        <td>
                            <a href="{{URL::to('/')}}/showThisProject?id={{$rec->project_id}}">{{$rec -> project_id}}</a>
                             @if($rec -> project_id == null)
                            <a href="{{ URL::to('/') }}/updateManufacturerDetails?id={{ $rec->manu_id }}">Manufacturer {{$rec -> manu_id}}</a>
                            @endif
                        </td>
                        <td>
                                <a href="{{ URL::to('/') }}/editenq?reqId={{ $rec->req_id }}" >{{$rec->req_id}}</a>
                        </td>
                        <td>{{ $rec->orderid }}  </td>
                        <td>{{$rec->name}}</td>
                        <td>
                            {{$rec -> main_category}}<br>
                            {{$rec -> sub_category}}<br>
                            {{$rec -> brand}}<br>
                        </td>
                        <td>{{$rec->quantity}} {{$rec->measurement_unit}}</td>
                        <td>
                          <?php 
                          $count = count($rec->ostatus);
                          ?>
                          @if($count == 1)
                          <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#logistics{{$rec->orderid}}">Logistics</button>
                          @else
                          <button disabled type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#logistics{{$rec->orderid}}">Logistics</button>
                          @endif
                        </td>
                        <td>{{ date('d-m-Y',strtotime($rec -> requirement_date)) }}</td>
                        <td class="text-center" id="paymenttd-{{$rec->orderid}}">
                            @if($rec->ostatus == "Payment Received")
                                {{ $rec->ostatus }}
                            @else
                                {{ $rec->ostatus }}
                            @endif
                        </td>
                        <td>
                            @if($rec->ostatus == "Payment Received")
                                <button class="btn btn-success btn-xs" data-toggle="modal" data-target="#paymentModal{{ $rec->orderid }}">
                                <?php $pay = explode(", ",$rec->payment_mode); 
                               
                                $pay = implode(" / ", $pay);        
                                ?>
                                   {{$pay}}
                                    <span class="badge">{{ $counts[$rec->orderid] }}</span>
                                   
                                </button>
                                <a href="{{URL::to('/')}}/paymentmode?id={{$rec->orderid}}&&pid={{$rec->project_id}}&&mid={{$rec->manu_id}}&&reqid={{$rec->id}}" target="_blank" class="btn btn-default btn-xs" ><i class="fa fa-plus"></i></a>
                            @elseif($rec->order_status != "Order Cancelled")
                                <a href="{{URL::to('/')}}/paymentmode?id={{$rec->orderid}}&&pid={{$rec->project_id}}&&mid={{$rec->manu_id}}&&reqid={{$rec->id}}" target="_blank" class="btn btn-success btn-xs">Payment Details</a>
                            @endif

</div>
</div>
                    <div id="payment{{$rec->orderid}}" class="modal fade" role="dialog">
                      <div class="modal-dialog" style="width:30%">

                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header" style="background-color: #5cb85c;color:white">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Confirm Payment</h4>
                          </div>
                          <div class="modal-body">
                                <table class="table table-responsive table-striped" border="1">
                                    <tr>
                                        <td>Payment Mode :</td>
                                        <td><?php $pay = explode(", ",$rec->payment_mode);
                                        $pay = implode(" / ", $pay);        
                                        ?>
                                   {{$pay}}</td>   
                                    </tr>
                                    <tr>
                                        <td>Category :</td>
                                        <td>{{ $rec->main_category }}</td>
                                    </tr>
                                    <tr>
                                        <td>Quantity :</td>
                                        <td>{{ $rec->quantity }}</td>
                                    </tr>
                                </table>
                           <form action="{{ URL::to('/') }}/confirmOrder?id={{$rec->orderid}}&&mid={{$rec->manu_id}}&&rid={{$rec->id}}" method="post">
                            {{ csrf_field() }}
                            <input type="hidden" name="cat" value="{{$rec->main_category}}">
                            <label> Total Quantity : </label>
                            <input readonly required type="number" class="form-control" name="quantity" placeholder="quantity" id="quan" onkeyup="checkthis('quan')" value="{{$rec->total_quantity}}">
                            <br>
                              
                               <label> State : </label><label class="alert-danger">{{$rec->st != null ? '' : "Select State From Enquiry"}}</label>
                            <select required name="state" class="form-control">
                                <option  value="{{ $rec->st != null ? $rec->st->id : ''}}">{{$rec->st != null ? $rec->st->state_name : '' }}</option>
                            </select>
                             
                            <br>
                            <label>Measurement Unit : </label>
                           <input  type="text" name="unit" value="{{$rec->cat != null ? $rec->cat->measurement_unit: ''}}" class="form-control" placeholder="Bags/Tons" required data-readonly>
                            <br>
                            <label>Mamahome Price(Per Unit) : </label>
                            <input required type="number" id="unit{{$rec->orderid}}"  class="form-control" name="mamaprice" placeholder="Unit Price"  value="{{$rec->price}}">
                            <input type="hidden" value="{{$rec->price}}" id="test1{{$rec->orderid}}">

                            <br>
                            <center><button class="btn btn-success" onclick="gothr('{{$rec->orderid}}')">Confirm</button></center>
                           
                            <br>
                           </form>
                          </div>
                          <div class="modal-footer">
                            <button  type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
<!-- Modal -->
<!-- Modal -->
<div id="logistics{{$rec->orderid}}" class="modal fade" role="dialog">
  <div class="modal-dialog" style="width:30%">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="background-color: #31b0d5;color: white;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Assign Logistic Coordinators</h4>
      </div>
      <div class="modal-body" >
       <form method="POST" id="assign" action="{{ url('/logistic')}}" >
          {{ csrf_field() }}
          <input type="hidden" name="logicid" value="{{$rec->orderid}}">
                            <div class="form-group">
                             <select size="7" id="menu{{$rec->orderid}}" name="framework[]" multiple class="form-control" style='overflow:hidden' required>
                            @foreach($users as $user)
                              <option  value="{{$user->id}}"> {{ $user->name }}</option>
                             @endforeach
                            </select> 
                              <button class="btn btn-success" type="submit">Submit</button>
                             </div> 
          </form>    
        @if($rec->logistic != null)
        <b>Assigned Logistic Coordinators : </b><br><br>
        <?php $topic_ids = explode(',', $rec->logistic);
      $users = App\User::whereIn('id', $topic_ids)->get();
        ?>
          @foreach($users as $user)
         <a href="#" data-toggle="tooltip" data-placement="right" title="
                    name : {{ $user->name}}
Department : {{ $user->department->dept_name }}
Designation : {{ $user->group->group_name }}
Personal Phone No : {{ $user->contactNo }}
Office Phone No : {{ $user->emp != null ? $user->emp->office_phone : '' }}"
           class="red-tooltip">{{ $user->name}}</a><br>
          @endforeach
        <br>
        @endif
                             <script type="text/javascript">
                                             $(document).ready(function(){
                                          @foreach($users as $user)
                                           $('#menu{{$rec->orderid}}').multiselect({
                                              nonSelectedText: 'Select Users',
                                              enableFiltering: true,
                                              enableCaseInsensitiveFiltering: true,
                                              buttonWidth:'200px',
                                               maxHeight: 200      
                                           });
                                           @endforeach
                                         });
                             </script>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<div id="supplier{{$rec->orderid}}{{$rec->manu_id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header" style="background-color: green;color:white;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"  style="text-align: center;">Supplier Invoice</h4>
      </div>
      <div class="modal-body">
        <form action="{{ URL::to('/') }}/supplierinvoice?id={{$rec->orderid}}&&mid={{$rec->manu_id}}&&project_id={{$rec->project_id}}" method="post"  enctype="multipart/form-data">
            {{ csrf_field() }}
            <table class="table table-responsive table-striped" border="1">
                <tr>
                    <td>
                      <label>Supplier Invoice Number : </label>
                    </td>
                    <td><input required type="text" name="supplierinvoice" class="form-control"></td>
                </tr>
                <tr>
                    <td>
                       <label> Invoice Date : </label>
                    </td>
                    <td>
                      <input required type="date" name="invoicedate" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Upload Files : </label>
                    </td>
                    <td>
                        <input required type="file" multiple name="file[]" class="form-control" accept="image/*"><br>
                         
                    </td>
                </tr>
            </table><center>
           <button type="submit" name="btnSubmit" align="center" class="btn btn-success">Submit</button></center>
       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!-- payment details modal -->
<!-- cancel modal -->
<!-- Modal -->
<div id="cancel{{$rec->orderid}}" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" style="width: 70%;">
      <div class="modal-header" style="background-color:#776e69;color: white">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cancel Order</h4>
      </div>
      <div class="modal-body">
                    <button href="{{URL::to('/')}}/storedetails" onclick="refund('{{$rec->orderid}}')" class=" btn btn-sm btn-success" >Refund</button>
                    <a href="{{URL::to('/')}}/storedetails"  onclick="show()" class=" btn btn-sm btn-danger " href="{{url()->previous()}}" >Adjust</a>
                    <br>
                    <div id="cancelorder{{$rec->orderid}}" style="display: none">
                    <form action="{{ URL::to('/') }}/savesupplierdetails?id={{$rec->orderid}}&&mid={{$rec->manu_id}}" method="post">
            {{ csrf_field() }}
                        <input type="text" name="orderid" value="{{$rec->orderid}}" id="orderid{{$rec->orderid}}" class="form-control" readonly>
                    </form>
                    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<script type="text/javascript">
    function refund(arg){

        var dvPassport = document.getElementById("cancelorder"+arg);

        dvPassport.style.display =  "block" ;
    }
</script>
<!-- end -->

<div id="purchase{{$rec->orderid}}{{$rec->manu_id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="background-color: green;color:white;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="text-align: center;">Purchase Order</h4>
      </div>
      <div class="modal-body">
        <form action="{{ URL::to('/') }}/savesupplierdetails?id={{$rec->orderid}}&&mid={{$rec->manu_id}}" method="post">
            {{ csrf_field() }}
       <!--  <input type="text" class="hidden" value="" id="dtow{{$rec->orderid}}" name="dtow" >
        <input type="text" class="hidden" value="" id="dtow1{{$rec->orderid}}" name="dtow1" > -->
        <input type="text" class="hidden" value="" id="cgstpercent{{$rec->orderid}}" name="cgstpercent" >
        <input type="text" class="hidden" value="" id="sgstpercent{{$rec->orderid}}" name="sgstpercent" >
        <input type="text" class="hidden" value="" id="gstpercent{{$rec->orderid}}" name="gstpercent" >
        <input type="text" class="hidden" value="" id="igstpercent{{$rec->orderid}}" name="igstpercent" >

       <table class="table table-responsive table-striped" border="1">
                                    <?php 
                                        $po =count($rec->purchase_order); 

                                     ?> 
                                @if($po == 0)
        
                                    <tr>
                                    <td>Category :</td>
                                    <td>
                                        <?php
                                                $s1 =  $rec->main_category;
                                        ?>
                                    <select required name="category" id="supply{{$rec->orderid}}"  class="form-control" >
                                        <option value="{{ $rec->main_category }}">{{ $rec->main_category }}</option>
                                      
                                    </select>
                                </td>
                                    </tr>
                                    <tr>
                                        <td>Supplier State : </td>
                                        <td>
                                            <label class="alert-danger">{{$rec->st != null ? '' : "Select State From Enquiry"}}</label>
                                            <select required id="state{{$rec->orderid}}"  name="state" class="form-control" >
                                                <?php
                                                $s2 = $rec->st != null ? $rec->st->id : '' ;
                                                $s3 = $rec->main_category;
                                                ?>
                                               <option value="{{ $rec->st != null ? $rec->st->id : ''}}">{{$rec->st != null ? $rec->st->state_name : '' }}
                                               </option>
                                            </select>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>Supplier Name :</td>
                                        <td> 
                                        <select required class="form-control" id="name{{$rec->orderid}}" name="name"  onchange="getaddress('{{$rec->orderid}}')">
                                          <option>--Select--</option>
                                     @foreach($manudetails as $manu)           
                                                 @if($s3 == $manu->category )
                                                    @if($s2 == $manu->state)
                                            <option value="{{$manu->company_name}}" >{{$manu->company_name}}</option>
                                              
                                                  @endif
                                                  @endif
                                    @endforeach
                                        </select>
                                      </td>

                                    </tr>
                                    <tr>
                                      <td>Registered Office :
                                      </td>
                                      <td><textarea required type="text" class="form-control" name="address" id="address{{$rec->orderid}}" name="address" rows="5" style="resize: none;">{{$rec->supplier != null ? $rec->supplier->registered_office : ''}}</textarea></td>
                                    </tr>
                                                <tr>
                                                    <td>Shipping Address : </td>
                                                    @if($rec->manu_id == null)
                                                    <td>
                                                    <textarea required type="text" class="form-control" name="ship"  rows="5" style="resize: none;">{{$rec->siteaddress != null ? $rec->siteaddress->address : ''}}</textarea>
                                                    </td>
                                                    @else
                                                    <td>
                                                    <textarea required type="text" class="form-control" name="ship"  rows="5" style="resize: none;">{{$rec->manu != null ? $rec->manu->address : ''}}</textarea>
                                                    </td>
                                                    @endif
                                                </tr>
                                                <tr>
                                                    <td>GST :</td>
                                                    <td><input required type="text" id="suppliergst{{$rec->orderid}}" name="gst" class="form-control" value="{{$rec->supplier != null ? $rec->supplier->gst : ''}}" ></td>
                                                </tr>
                                                <tr>
                                                    <td>Description of Goods : </td>
                                                    <td><input required type="text" name="desc" id="desc{{$rec->orderid}}" class="form-control" value="{{$rec->supplier != null ? $rec->supplier->category : ''}}" ></td>
                                                </tr>
                                                 <tr>
                                                    <td>Unit of Measurement:</td>
                                                    <td><input required type="unit" name="munit" id="munit{{$rec->orderid}}" class="form-control" value="{{$rec->cat != null ? $rec->cat->measurement_unit: ''}}" ></td>
                                                </tr>
                                    <tr>
                                        <td>Quantity : </td>
                                        <td><input required type="number" name="quantity" class="form-control" id="qu{{$rec->orderid}}" value="{{$rec->total_quantity}}" onkeyup="showthis('{{$rec->orderid}}')"></td>
                                    </tr>
                                    <tr>
                                        <td> Supplier Unit Price :</td>
                                        <td>@if($rec->price != null)
                                            <label class="alert-success">Enquiry price : {{$rec->price}}</label>
                                            <input type="hidden" value="{{$rec->price}}" id="test{{$rec->orderid}}">
                                            @endif
                                            <input required type="number" id="unitprice{{$rec->orderid}}" name="uprice" class="form-control" onkeyup="showthis('{{$rec->orderid}}')" value="" >
                                       </td>
                                    </tr>
                                    <tr>
                                          <td>Unit Price without GST :</td>
                                        <td>&nbsp;&nbsp;&nbsp;<label class=" alert-success pull-left" id="withoutgst{{$rec->orderid}}"></label>Rs./-
                                             <input  id="withoutgst1{{$rec->orderid}}" type="hidden" name="unitwithoutgst" value="">
                                       </td>
                                    </tr>
                                    <tr>
                                        <td>Total Amount : </td>
                                        <td>
                                              &nbsp;&nbsp;&nbsp;RS .<label class=" alert-success pull-left" id="display{{$rec->orderid}}"></label>/-
                                        </td>
                                    </tr>
                                    <tr>
                                        
                                        <td>CGST( <label  id="tax1{{$rec->orderid}}"></label>%) : </td>
                                        <td>

                                              &nbsp;&nbsp;&nbsp;CGST <label class=" alert-success pull-left" id="cgst{{$rec->orderid}}"></label>/-
                                        </td>
                                    </tr>
                                     <tr>
                                        <td>SGST( <label  id="tax2{{$rec->orderid}}"></label>%) : </td>
                                        <td>
                                             &nbsp;&nbsp;&nbsp;SGST <label class=" alert-success pull-left" id="sgst{{$rec->orderid}}"></label>/-
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>IGST( <label  id="tax3{{$rec->orderid}}"></label>%) : </td>
                                        <td>
                                             &nbsp;&nbsp;&nbsp;IGST <label class=" alert-success pull-left" id="igst{{$rec->orderid}}"></label>/-
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Amount (Including GST) :</td>
                                        <td>
                                              &nbsp;&nbsp;&nbsp;RS .<label class=" alert-success pull-left" id="withgst{{$rec->orderid}}"></label> /-
                                        </td>
                                    </tr>
                                    @else

                                                 @foreach($suppliers as $supply)
                                                 @if($supply->order_id == $rec->orderid)
                                                             <tr>
                                                <td>Category :</td>
                                                <td>
                                                <select required name="category" id="supply{{$rec->orderid}}"  class="form-control" >
                                                   
                                                    <option value="{{ $supply->category }}">{{ $supply->category }}</option>
                                                   
                                                </select>
                                            </td>
                                                </tr>
                                    <tr>
                                            <td>Supplier State : </td>
                                            <td>
                                              
                                              
                                            <select id="state{{$rec->orderid}}" name="state" class="form-control">
                                                 <option value="{{ $rec->st != null ? $rec->st->id : ''}}">{{$supply->st != null ? $supply->st->state_name : '' }}
                                               </option>
                                            </select>
                                              
                                                            
                                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Supplier Name :</td>
                                        <td> 
                                        <input required class="form-control"  name="name"  value="{{$supply->supplier_name}}"> 
                                      </td>

                                    </tr>
                                    
                                                <tr>
                                                  <td>Registered Office :
                                                  </td>
                                                  <td><textarea required type="text" class="form-control" rows="5" name="edit1" style="resize: none;">{{$supply->address}}</textarea></td>
                                                </tr>
                                                <tr>
                                                    <td>Shipping Address :
                                                  </td>
                                                    <td><textarea required type="text" class="form-control" name="edit2"  rows="5" style="resize: none;">{{$supply->ship}}</textarea></td>
                                                </tr>
                                                 <tr>
                                                    <td>GST :</td>
                                                    <td><input required type="text"  name="edit3" value="{{$supply->gst}}" class="form-control" ></td>
                                                </tr>
                                                <tr>
                                                    <td>Description of Goods : </td>
                                                    <td><input required type="text" name="edit4" class="form-control" value="{{$supply->description}}" ></td>
                                                </tr>
                                                 <tr>
                                                    <td>Unit of Measurement:</td>
                                                    <td><input required type="unit" name="edit5" class="form-control" value="{{$supply->unit}}" ></td>
                                                </tr>
                                                <tr>
                                                    <td>Quantity : </td>
                                                    <td><input required type="number" name="edit6" id="qu{{$rec->orderid}}" class="form-control"  value="{{$supply->quantity}}" onkeyup="showthis('{{$rec->orderid}}')"></td>
                                                </tr>
                                                <tr>
                                                    <td> Supplier Unit Price :</td>
                                                    <td>
                                                        <input required type="number" id="unitprice{{$rec->orderid}}" name="uprice" class="form-control" onkeyup="showthis('{{$rec->orderid}}')" value="{{$supply->unit_price}}">
                                                         <input type="hidden" value="{{$rec->price}}" id="test{{$rec->orderid}}">
                                                   </td>
                                                </tr>
                                                <tr>
                                                <td>Unit Price without GST :</td>
                                                <td>&nbsp;&nbsp;&nbsp;RS .<label class=" alert-success pull-left" id="withoutgst{{$rec->orderid}}"></label>/-
                                                    <input readonly id="withoutgst1{{$rec->orderid}}" type="text" name="unitwithoutgst" value="{{$supply->unitwithoutgst}}"> 
                                               </td>
                                                </tr>
                                                <tr>
                                        <td>Total Amount : </td>
                                        <td>
                                              &nbsp;&nbsp;&nbsp;RS .<label class=" alert-success pull-left" id="display{{$rec->orderid}}"></label>/-
                                               
                                                    <input readonly type="text" name="" value="{{$supply->amount}}">
                                           
                                        </td>
                                    </tr>
                                    <tr>
                                            <?php
                                    $t1 = ($supply->amount * $supply->cgstpercent)/100;
                                    $t2 = ($supply->amount * $supply->sgstpercent)/100;
                                    $t3 = ($supply->amount * $supply->igstpercent)/100;
                                            ?>
                                        
                                        <td>CGST(<label  id="tax1{{$rec->orderid}}">{{$supply->cgstpercent}}</label>%) : </td>
                                        <td>
                                              &nbsp;&nbsp;&nbsp;CGST <label class=" alert-success pull-left" id="cgst{{$rec->orderid}}"></label>/-
                                              <input readonly type="text" name="" value="{{$t1}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>SGST(<label  id="tax2{{$rec->orderid}}"> {{$supply->sgstpercent}}</label>%) : </td>
                                        <td>
                                             &nbsp;&nbsp;&nbsp;SGST <label class=" alert-success pull-left" id="sgst{{$rec->orderid}}"></label>/-
                                             <input readonly name="" value="{{$t2}}" type="text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>IGST( <label  id="tax3{{$rec->orderid}}">{{$supply->igstpercent}}</label>%) : </td>
                                        <td>
                                             &nbsp;&nbsp;&nbsp;IGST <label class=" alert-success pull-left" id="igst{{$rec->orderid}}"></label>/-
                                             <input readonly type="text" name="" value="{{$t3}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Amount (Including GST) :</td>
                                        <td>
                                              &nbsp;&nbsp;&nbsp;RS .<label class=" alert-success pull-left" id="withgst{{$rec->orderid}}"></label> /-
                                             
                                                    <input readonly type="text" name="" value="{{$supply->totalamount}}">
                                            
                                        </td>
                                    </tr>
                                        @endif
                                        @endforeach        
                                    @endif
                                        <input id="amount{{$rec->orderid}}" required type="hidden" name="amount" maxlength="9"   class="form-control" />
                             <label class=" alert-success pull-right" id="lblWord{{$rec->orderid}}"></label>
                                       <input  id="tamount{{$rec->orderid}}" type="hidden" name="totalamount" maxlength="9"  class="form-control" />
                             <label class=" alert-success pull-right" id="lblWord1{{$rec->orderid}}"></label>
                               
        </table>
        <button  class="btn btn-success" onclick="fill('{{$rec->orderid}}')">Submit</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
                             <!-- The Modal -->
      <div class="modal" id="paymentModal{{ $rec->orderid }}">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header" style="width:100%;padding:2px;background-color:green;">
        <center>  <h4 class="modal-title" style="color: white;">Payment Details</h4></center>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
            @foreach($paymentDetails as $payment)
            @if($payment->order_id == $rec->orderid)
            <table class="table table-responsive table-striped" border="1">
              <tr>
                <td>OrderId :</td>
                <td>{{$payment->order_id}}</td>
              </tr>
              <tr>
                <td>Payment Mode :</td>
                <td>
                    {{ $payment->payment_mode }}</td>
              </tr>
              @if($payment->payment_mode == "CASH")
              <tr>
                <td>Cash Deposit Slip :</td>
                <td>
                  <?php
                                                     $images = explode(",", $payment->file );
                                                    ?>
                                                   <div class="col-md-12">
                                                       @for($i = 0; $i < count($images); $i++)
                                                           <div class="col-md-3">
                                                                <img height="350" width="350" id="project_img" src="{{ URL::to('/') }}/public/payment_details/{{ $images[$i] }}" class="img img-thumbnail">
                                                           </div>
                                                       @endfor
                                                    </div>
                </td>
              </tr>
               <tr>
                <td>Cash Deposit Date :</td>
                <td>{{ date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
               @foreach($denoms as $denom)
              @if($denom->order_id == $rec->orderid && $denom->multiple_pay == null)
              <!-- denomination -->
              <tr>
                <td>Denomination :</td>
                <td>
                  <table class="table table-hover">
                    <tr><td>Notes</td>
                    <td>Count</td>
                    <td>Total</td>
                    </tr>
                     
                    <tr>
                      @if($denom->x2000 != null)
                      <td>x2000</td>
                      <td>{{$denom->x2000}}</td>
                      <td>{{2000 * $denom->x2000}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x500 != null)
                      <td>x500</td><td>{{$denom->x500}}</td>
                      <td>{{500 * $denom->x500}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x200 != null)
                      <td>x200</td><td>{{$denom->x200}}</td>
                      <td>{{200 * $denom->x200}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x100 != null)
                      <td>x100</td><td>{{$denom->x100}}</td>
                      <td>{{100 * $denom->x100}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x50 != null)
                      <td>x50</td><td>{{$denom->x50}}</td>
                      <td>{{50 * $denom->x50}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x20 != null)
                      <td>x20</td><td>{{$denom->x20}}</td>
                      <td>{{20 * $denom->x20}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x10 != null)
                      <td>x10</td><td>{{$denom->x10}}</td>
                      <td>{{10 * $denom->x10}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x5 != null)
                      <td>x5</td><td>{{$denom->x5}}</td>
                      <td>{{5 * $denom->x5}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x1 != null)
                      <td>x1</td><td>{{$denom->x1}}</td>
                      <td>{{1 * $denom->x1}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->total != null)
                      <td>Total</td>
                      <td></td>
                      <td>{{$denom->total}}</td>
                      @endif
                    </tr>
                  </table>
                </td>
              </tr>
              <!-- end -->
              @endif
              @endforeach
              @endif
              @if($payment->payment_mode == "RTGS")
              <tr>
                  <td>RTGS Image: </td>
                  <td>
                      <?php
                             $images = explode(",", $payment->rtgs_file );
                            ?>
                           <div class="col-md-12">
                               @for($i = 0; $i < count($images); $i++)
                                   <div class="col-md-3">
                                        <img height="350" width="350" id="project_img" src="{{ URL::to('/') }}/public/rtgs_files/{{ $images[$i] }}" class="img img-thumbnail">
                                   </div>
                               @endfor
                            </div>
                  </td>
              </tr>
               <tr>
                <td>Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              <tr>
                <td>Reference Number :</td>
                <td>{{$payment->account_number}}<br></td>
              </tr>
              <tr>
                <td>Branch Name :</td>
                <td>{{$payment->branch_name}}<br></td>
              </tr>
              @endif
              @if($payment->payment_mode == "CHEQUE")
               <tr>
                <td>Cheque Deposit Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              <tr>
                <td>Cheque Number :</td>
                <td>{{$payment->cheque_number}}
                </td>
              </tr>
              @endif
              @if($payment->payment_mode == "CASH IN HAND")
              <tr>
                <td>Cash Holder Name : </td>
                <td>{{$payment->user != null?$payment->user->name :''}}</td>
              </tr>
                 <tr>
                <td> Cash Received Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              @endif
              <tr>
                <td>Total Amount :</td>
                <td>{{$payment->totalamount}}/-</td>
              </tr>
              <tr>
                <td>Delivery Charges :</td>
                <td>{{$payment->damount}}/-</td>
              </tr>
              <tr>
                <td>Note :</td>
                <td>{{$payment->payment_note}}</td>
              </tr>
            </table>
              <!-- <img src="{{ URL::to('/') }}/payment_details/{{ $payment->file }}" alt="" class="img img-responsive"> -->
            @endif
            @endforeach
            @foreach($payhistory as $payment)
            @if($payment->order_id == $rec->orderid)
                <table class="table table-responsive table-striped" border="1">
              <tr>
                <td>OrderId :</td>
                <td>{{$payment->order_id}}</td>
              </tr>
              <tr>
                <td>Payment Mode :</td>
                <td>{{ $payment->payment_mode }}</td>
              </tr>
              @if($payment->payment_mode == "CASH")
              <tr>
                <td>Cash Deposit Slip :</td>
                <td>
                  <?php
                                                     $images = explode(",", $payment->file );
                                                    ?>
                                                   <div class="col-md-12">
                                                       @for($i = 0; $i < count($images); $i++)
                                                           <div class="col-md-3">
                                                                <img height="350" width="350" id="project_img" src="{{ URL::to('/') }}/public/payment_details/{{ $images[$i] }}" class="img img-thumbnail">
                                                           </div>
                                                       @endfor
                                                    </div>
                </td>
              </tr>
               <tr>
                <td>Cash Deposit Date :</td>
                <td>{{ date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              @foreach($denoms as $denom)
              @if($denom->order_id == $rec->orderid && $denom->multiple_pay != null)
              <!-- denomination -->
              <tr>
                <td>Denomination :</td>
                <td>
                  <table class="table table-hover">
                    <tr>
                      <td>Notes</td>
                      <td>Count</td>
                      <td>Total</td>
                    </tr>
                    <tr>
                      @if($denom->x2000 != null)
                      <td>x2000</td>
                      <td>{{$denom->x2000}}</td>
                      <td>{{2000 * $denom->x2000}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x500 != null)
                      <td>x500</td><td>{{$denom->x500}}</td>
                      <td>{{500 * $denom->x500}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x200 != null)
                      <td>x200</td><td>{{$denom->x200}}</td>
                      <td>{{200 * $denom->x200}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x100 != null)
                      <td>x100</td><td>{{$denom->x100}}</td>
                      <td>{{100 * $denom->x100}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x50 != null)
                      <td>x50</td><td>{{$denom->x50}}</td>
                      <td>{{50 * $denom->x50}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x20 != null)
                      <td>x20</td><td>{{$denom->x20}}</td>
                      <td>{{20 * $denom->x20}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x10 != null)
                      <td>x10</td><td>{{$denom->x10}}</td>
                      <td>{{10 * $denom->x10}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x5 != null)
                      <td>x5</td><td>{{$denom->x5}}</td>
                      <td>{{5 * $denom->x5}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->x1 != null)
                      <td>x1</td><td>{{$denom->x1}}</td>
                      <td>{{1 * $denom->x1}}</td>
                      @endif
                    </tr>
                    <tr>
                      @if($denom->total != null)
                      <td>Total</td>
                      <td></td>
                      <td>{{$denom->total}}</td>
                      @endif
                    </tr>
                  </table>
                </td>
              </tr>
              <!-- end -->
              @endif
              @endforeach
              @endif
              @if($payment->payment_mode == "RTGS")
              <tr>
                  <td>RTGS Image: </td>
                  <td>
                      <?php
                             $images = explode(",", $payment->rtgs_file );
                            ?>
                           <div class="col-md-12">
                               @for($i = 0; $i < count($images); $i++)
                                   <div class="col-md-3">
                                        <img height="350" width="350" id="project_img" src="{{ URL::to('/') }}/public/rtgs_files/{{ $images[$i] }}" class="img img-thumbnail">
                                   </div>
                               @endfor
                            </div>
                  </td>
              </tr>
               <tr>
                <td>Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              <tr>
                <td>Reference Number :</td>
                <td>{{$payment->account_number}}<br></td>
              </tr>
              <tr>
                <td>Branch Name :</td>
                <td>{{$payment->branch_name}}<br></td>
              </tr>
              @endif
              @if($payment->payment_mode == "CHEQUE")
               <tr>
                <td>Cheque Deposit Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              <tr>
                <td>Cheque Number :</td>
                <td>{{$payment->cheque_number}}
                </td>
              </tr>
              @endif
              @if($payment->payment_mode == "CASH IN HAND")
              <tr>
                <td>Cash Holder Name : </td>
                <td>{{$payment->user != null?$payment->user->name :''}}</td>
              </tr>
                 <tr>
                <td> Cash Received Date :</td>
                <td>{{date('d-m-Y',strtotime($payment->date))}}</td>
              </tr>
              @endif
              <tr>
                <td>Total Amount :</td>
                <td>{{$payment->totalamount}}/-</td>
              </tr>
              <tr>
                <td>Delivery Charges :</td>
                <td>{{$payment->damount}}/-</td>
              </tr>
              <tr>
                <td>Note :</td>
                <td>{{$payment->payment_note}}</td>
              </tr>
            </table>
            @endif
            @endforeach
            <hr>
            <div class="row">
                <div class="col-md-12">
                    Messages: <br>
                    @foreach($messages as $message)
                        @if($message->to_user == $rec->orderid)
                            <p
                                style="width:70%;
                                    border-style:ridge;
                                    padding:10px;
                                    border-width:2px;
                                    border-radius:10px;
                                    {{ $message->from_user == Auth::user()->id ? 'border-bottom-left-radius:0px;' : 'border-bottom-right-radius:0px;' }}
                                    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);"
                                    class="text-justify {{ $message->from_user == Auth::user()->id ? 'pull-right' : 'pull-left' }}">
                                @foreach($chatUsers as $user)
                                    @if($user->id == $message->from_user)
                                        <b>- {{ $user->name }} : </b><br>
                                    @endif
                                @endforeach
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ $message->body }}
                                <br>
                                <span class="pull-right"><i>{{ $message->created_at->diffforHumans() }}</i></span>
                            </p>
                        @endif
                    @endforeach
                </div>
                <div class="col-md-12">
                    <form action="{{ URL::to('/') }}/sendMessage" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="orderId" value="{{ $rec->orderid }}">    
                        <div class="input-group">
                            <input type="text" name="message" id="message" placeholder="Type Your Message Here" class="form-control">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-success">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>        
        <!-- Modal footer -->
        <div class="modal-footer" style="padding:2px">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
  
</div>
</td>

                        <td>
                          @foreach($suppliers as $supply)
                            @if($supply->order_id == $rec->orderid)
                            {{$supply->lpo}}
                            @endif
                          @endforeach
                        </td>
                        
                        <!-- <td>
                            <a href="{{URL::to('/')}}/{{$rec->orderid}}/printLPO" target="_blank" class="btn btn-sm btn-primary" >Print Invoice</a>
                        </td> -->
                        <td>
                            @if($rec->order_status == "Enquiry Confirmed" && ($rec->ostatus == "Payment Received"))
                            <div class="btn-group">
                                <!-- <a class="btn btn-xs btn-success" href="{{URL::to('/')}}/confirmOrder?id={{ $rec->orderid }}">Confirm</a> -->
                                <button type="button" class="btn btn-xs btn-success" data-toggle="modal" data-target="#payment{{$rec->orderid}}"> Confirm</button>
                                <button class="btn btn-xs btn-danger pull-right" data-toggle="modal" data-target="#cancel{{$rec->orderid}}" >Cancel</button>
                            </div>
                            @else
                           {{ $rec->order_status }}
                            @endif
                          </td>
                         
                          <td>
                     
                        @if($rec->purchase_order == "yes"  )
                            @if($rec->manu_id != null)
                            <a href="{{ route('downloadpurchaseOrder',['id'=>$rec->orderid,'mid'=>$rec->manu_id]) }}" class="btn btn-xs" style="background-color: rgb(204, 102, 153);color:white;">Manufacturer Purchase Order</a>
                            @else
                             <a href="{{ route('downloadpurchaseOrder',['id'=>$rec->orderid]) }}" class="btn btn-xs" style="background-color: rgb(204, 102, 153);color:white;">Purchase Order</a>
                              @endif
                          @else
                          @if($rec -> project_id == null)
                            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#purchase{{$rec->orderid}}{{$rec->manu_id}}">Get Manufacturer Purchase Order</button>
                            @else
                                <button type="button" class="btn btn-success btn-xs"  data-toggle="modal" data-target="#purchase{{$rec->orderid}}{{$rec->manu_id}}">Get Purchase Order</button>
                          @endif
                         @endif
                     </td>
                    <td>
                     @foreach($invoice as $inv)
                    @if($inv->order_id == $rec->orderid)
                    <a href="{{ route('downloadSupplierInvoice',['id'=>$rec->orderid,'mid'=>$rec->manu_id]) }}" class="btn btn-xs" style="background-color: rgb(204, 102, 153);color:white;">Supplier Invoice</a>
                        @endif
                     @endforeach
                  <?php 
                                $sp =count($rec->supplier_invoice);
                             ?> 
                    @if($sp == 0)
                    <button  type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#supplier{{$rec->orderid}}{{$rec->manu_id}}">Input Supplier Invoice</button>
                    @endif
                  
                     
                  
                  </td>                     
                       <td>

                             <div class="btn-group">
                                <!-- <a class="btn btn-xs btn-success" href="{{URL::to('/')}}/confirmOrder?id={{ $rec->orderid }}">Confirm</a> -->
                               
                                <!-- <a href="{{ URL::to('/') }}/editenq?reqId={{ $rec->id }}" class="btn btn-xs btn-primary">Edit</a> -->
                            <?php 
                                $po =count($rec->purchase_order); 

                             ?> 
                                @if($po == 0)
                                        <button disabled type="button" class="btn btn-primary btn-xs">Edit</button>
                                        <a href="{{ URL::to('/') }}/cancelOrder?id={{$rec->orderid}}" class="btn btn-xs btn-danger pull-right" >Cancel</a>
                                @else
                                        <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#purchase{{$rec->orderid}}{{$rec->manu_id}}">Edit</button>
                                        <a href="{{ URL::to('/') }}/cancelOrder?id={{$rec->orderid}}" class="btn btn-xs btn-danger pull-right" >Cancel</a>
                                @endif
                          
                            </div>
                       </td>

                    </tr>
                    @endforeach
                </tbody>    
            </table>
            <br>
            <center>{{$view->links()}}</center>    
        </div>
    </div>
</div>


<script type="text/javascript">
 

    function pay(arg)
    {
        var e = document.getElementById("selectPayment-"+arg);
        var strUser = e.options[e.selectedIndex].value;
        var ans = confirm('Are You Sure ? Note: Changes Made Once CANNOT Be Undone');
        if(ans){
            $.ajax({
                type: 'GET',
                url: "{{URL::to('/')}}/updateampay",
                data: {payment: strUser, id: arg},
                async: false,
                success: function(response){
                    console.log(response);
                }
            });
        }
        return false;
    }

    function updateDispatch(arg)
    {
        var e = document.getElementById("selectdispatch-"+arg);
        var strUser = e.options[e.selectedIndex].value;
        var ans = confirm('Are You Sure ? Note: Changes Made Once CANNOT Be Undone');
        if(ans){
            $.ajax({
                type: 'GET',
                url: "{{URL::to('/')}}/updateamdispatch",
                data: {dispatch: strUser, id: arg},
                async: false,
                success: function(response){
                    console.log(response);    
                }
            });
        }
        return false;    
    }
    
    function confirmOrder(arg)
    {
        var ans = confirm('Are You Sure To Confirm This Order ?');
        if(ans)
        {
            $.ajax({
               type:'GET',
               url: "{{URL::to('/')}}/confirmOrder",
               data: {id : arg},
               async: false,
               success: function(response)
               {
                   console.log(response);
                        alert(response);
                   $("#myordertable").load(location.href + " #myordertable>*", "");
               }
            });
        }    
    }
    
    function cancelOrder(arg)
    {
        var ans = confirm('Are You Sure To Cancel This Order ?');
        if(ans)
        {
            $.ajax({
                type:'GET',
                url: "{{URL::to('/')}}/cancelOrder",
                data: {id : arg},
                async: false,
                success: function(response)
                {
                   console.log(response);
                   $("#myordertable").load(location.href + " #myordertable>*", "");
                }
            });
        }
    }
</script>
<script type="text/javascript">
    function paymethod(){
        var input = document.getElementById("payment_mode").value;
       if(input == "RTGS"){
            document.getElementById("input1").className = "";
       }
       else if(input == "CASH"){
            document.getElementById("payment_slip").className = "";
            document.getElementById("lb1").className = "";
            document.getElementById("input1").className = "";
       }
       
    }
</script>
<script type="text/javascript">
function description(arg) {
     var z = document.getElementById('supply'+arg);
  var name = z.options[z.selectedIndex].value;
  document.getElementById('category'+arg).value = name;
}
function fill(arg){
  var x =document.getElementById('unitprice'+arg).value;
  var y =document.getElementById('test'+arg).value;

  if(x > y){
    document.getElementById('unitprice'+arg).value = "";
    alert("Purchase Order Price should be Less Than Enquiry Price");
  }
}
function showthis(arg){

  
  var z = document.getElementById('supply'+arg);
  var name = z.options[z.selectedIndex].value;
  var x = document.getElementById('state'+arg);
  var state = x.options[x.selectedIndex].value;

if(name == "CEMENT" && state == "1"){
    var percent = 1.28;
    var gstvalue = 14;
    var sgstvalue = 14;
     var igstvalue = "";
}
else if(name == "CEMENT" && state == "2"){
    var percent = 1.28;
    var gstvalue = 14;
    var sgstvalue = 14;
    var igstvalue = 28;
}
else if(name == "M-SAND" && state == "1"){
    var percent = 1.05;
    var gstvalue = 2.5;
    var sgstvalue = 2.5;
    var igstvalue = "";
}
else if(name == "M-SAND" && state == "2"){
    var percent = 1.05;
    var gstvalue = 2.5;
    var sgstvalue = 2.5;
    var igstvalue = 5;
}
else if( (state == "1") && (name == "PLUMBING" || "STEEL" || "ELECTRICALS") ){
    var percent = 1.18;
    var gstvalue = 9;
    var sgstvalue = 9;
    var igstvalue = "";

   
}
else if( (state == "2") && (name == "PLUMBING" || "STEEL" || "ELECTRICALS") ){
    var percent = 1.18;
    var gstvalue = 9;
    var sgstvalue = 9;
    var igstvalue = 18;

}
else{
    var percent = 1.28;
    var gstvalue = 14;
    var sgstvalue = 14;
    var igstvalue = "";
}
var g1 = gstvalue;
var g2 = sgstvalue;
document.getElementById('tax1'+arg).innerHTML = g1;
document.getElementById('tax2'+arg).innerHTML = g2;
if(igstvalue != ""){
    
var g3 = igstvalue;
document.getElementById('tax3'+arg).innerHTML = g3;
}
else{
   
    var g3 = "";
document.getElementById('tax3'+arg).innerHTML = g3;
}
var x =document.getElementById('unitprice'+arg).value;
var y = document.getElementById('qu'+arg).value;
var withoutgst = (x /percent);
var i = parseFloat(withoutgst).toFixed(2);
var t = (withoutgst * y);
var f = Math.round(t);
var gst = (t * gstvalue)/100;
var sgt = (t * sgstvalue)/100;
var igst = (gst + sgt);
var withgst = (gst + sgt + t);
var final = Math.round(withgst);
document.getElementById('cgstpercent'+arg).value = gstvalue;
document.getElementById('sgstpercent'+arg).value = sgstvalue;
document.getElementById('gstpercent'+arg).value = percent;
document.getElementById('igstpercent'+arg).value = igstvalue;
document.getElementById('display'+arg).innerHTML = t;
document.getElementById('cgst'+arg).innerHTML = gst;
document.getElementById('sgst'+arg).innerHTML = sgt;
if(igstvalue != ""){
document.getElementById('igst'+arg).innerHTML = igst;
}
else{
    document.getElementById('igst'+arg).innerHTML = "";
}

document.getElementById('withgst'+arg).innerHTML = withgst;
document.getElementById('withoutgst'+arg).innerHTML = i;
document.getElementById('withoutgst1'+arg).value = i;
document.getElementById('amount'+arg).value = f;
document.getElementById('tamount'+arg).value = final;
}

function gothr(arg){
  var x =document.getElementById('unit'+arg).value;
  var y =document.getElementById('test1'+arg).value;
  if(x < y){
      document.getElementById('unit'+arg).value = "";
      alert("Mamahome Price Cannot be Less Than Enquiry Price");
  }
}
function getaddress(arg){
  var x = document.getElementById('name'+arg);
  var name = x.options[x.selectedIndex].value;
  var x = arg;
  $.ajax({
                    type:'GET',
                    url:"{{URL::to('/')}}/getgst",
                    async:false,
                    data:{name : name , x : x},
                    success: function(response)
                    {
                       
                                                 for(var i=0;i<response.length;i++)
                        {
                           var text = response[i].cin;
                        }
                        var id = response.id;
                        var name = response.res;
                        var gst = response.gst;
                        var cat = response.category;
                        var unit = response.unit;
                         document.getElementById('address'+id).value = name; 
                         document.getElementById('suppliergst'+id).value = gst;
                         document.getElementById('desc'+id).value = cat;
                         document.getElementById('munit'+id).value = unit; 
                    }
                });
            }
</script>
<script type="text/javascript">
function getsuppliername(arg) {
  var x = document.getElementById('supply'+arg);
  var name = x.options[x.selectedIndex].value;
  var y = document.getElementById('state'+arg);
  var state = y.options[y.selectedIndex].value;
  var x = arg;
  $.ajax({
                    type:'GET',
                    url:"{{URL::to('/')}}/getsupplier",
                    async:false,
                    data:{name : name , x : x , state : state},
                    success: function(response)
                    {

                        
                       var id = response[0]['id'];
                        
                        var html = "<option value='' disabled selected>---Select---</option>";
                        for(var i=0; i< response[0]['supplier'].length; i++)
                        {
                            html += "<option value='"+response[0]['supplier'][i]['company_name']+"'>"+response[0]['supplier'][i]['company_name']+"</option>";
                        }
                        document.getElementById('name'+id).innerHTML = html;
                    }
                });
    }
</script>
 <script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
     background-color: #00acd6 
});
</script>
<script src="http://www.ittutorials.in/js/demo/NumToWord.js; type="text/javascript"></script>
@endsection
