@extends('layouts.amheader')
@section('content')
<div class="col-md-12">
	<div class="panel panel-default" style="overflow-x: scroll;border-color:green">
		<div class="panel-heading text-center" style="background-color:green">
			<b style="color:white;font-size:1.4em">Orders</b>
			<a class="pull-right btn btn-sm btn-danger" href="{{ url()->previous() }}" id="btn1" style="color:white;"><b>Back</b></a>
		</div>
		<div class="panel-body">
		    <form method="GET" action="{{URL::to('/')}}/amorderss">
		    <table class="table table-responsive table-hover" style="width:70%">
		        <tbody>
		            <tr>
		                <td style="width:15%">
		                    From Date : 
		                </td>
		                <td style="width:25%">
		                    <input type="date" class="form-control" id="fromdate" name="fromdate"/>
		                </td>
		                <td style="width:15%">
		                    To Date :
		                </td>
		                <td style="width:25%">
		                    <input type="date" class="form-control" id="todate" name="todate" />
		                </td>
		                <td style="width:20%">
		                    <input type="submit" class="btn btn-md btn-primary" id="filter" style="width:100%" name="filter" value="Filter" />
		                </td>
		            </tr>        
		        </tbody>
		    </table>
		    </form>
		    <table class="table table-responsive table-striped" border="1" id='table'>
				<thead>
				    <th style="text-align:center">Project ID</th>
				    <th style="text-align:center" class="{{ Auth::user()->department_id == 1 && Auth::user()->group_id == 2?'hidden':''}}">Generated By</th>
				    <th style="text-align:center" class="{{ Auth::user()->department_id == 1 && Auth::user()->group_id == 2?'hidden':''}}">Designation</th>
				    <th style="text-align:center">Procurement Name</th>
					<th style="text-align:center">Main Category</th>
					<th style="text-align:center">Sub Category</th>
					<th style="text-align:center">Quantity</th>
					<th style="text-align:center">Status</th>
					<th style="text-align:center">Requirement Date</th>
					@if(Auth::user()->department_id == 5 && Auth::user()->group_id == 4)
					<!--<th style="text-align:center">Payment Status</th>-->
					<th style="text-align:center">Dispatch Status</th>
					<th style="text-align:center">Delivery Status</th>
					<th style="text-align:center">Print</th>
					<th style="text-align:center">Action</th>
					@endif
				</thead>
				<tbody>
					@foreach($view as $rec)
					<tr id="row-{{$rec->id}}">
						<td style="text-align:center"><a href="{{URL::to('/')}}/amshowProjectDetails?projectId={{$rec->project_id}}">{{$rec -> project_id}}</a></td>
						<td style="text-align:center" class="{{ Auth::user()->department_id == 1 && Auth::user()->group_id == 2?'hidden':''}}">{{ $rec->name }}</td>
						<td style="text-align:center" class="{{ Auth::user()->department_id == 1 && Auth::user()->group_id == 2?'hidden':''}}">
						    @if($rec->group_id == '6')
						    Listing Engineer
						    @elseif($rec->group_id == '7')
						    Sales Engineer
						    @endif
						</td>
						<td style="text-align:center">{{$rec->procurement_name}}</td>
						<td style="text-align:center">{{$rec->main_category}}</td>
						<td style="text-align:center">{{$rec->sub_category}}</td>
						<td style="text-align:center">{{$rec->quantity}} {{$rec->measurement_unit}}</td>
						<td style="text-align:center">{{$rec->status}}</td>
						<td style="text-align:center" id="tddate{{$rec->id}}">{{$rec -> requirement_date}}</td>
						@if(Auth::user()->department_id == 5 && Auth::user()->group_id == 4)
                        <!--<td style="text-align:center" id="paymenttd-{{$rec->id}}">-->
                        <!--    <select id="selectPayment-{{$rec->id}}" class="form-control" name="selectPayment-{{$rec->id}}" onchange="pay('{{$rec->id}}')">-->
                        <!--        <option value="" disabled selected>-- SELECT --</option>-->
                        <!--        <option value="Payment Received" {{$rec->payment_status == 'Payment Received'?'selected':''}}>Payment Received</option>-->
                        <!--        <option value="Payment Pending" {{$rec->payment_status == 'Payment Pending'?'selected':''}}>Payment Pending</option>-->
                        <!--    </select>-->
                        <!--</td>-->
                        <td style="text-align:center">
                            @if($rec->status === 'Order Confirmed')
                            <select id="selectdispatch-{{$rec->id}}" class="form-control" name="selectdispatch-{{$rec->id}}" onchange="updateDispatch('{{$rec->id}}')">
                                <option value="" disabled selected>-- SELECT --</option>
                                <option value="Dispatched" {{$rec-> dispatch_status == 'Dispatched' || $rec->dispatch_status == 'Yes'?'selected':''}}>Dispatched</option>
                                <option value="Not yet dispatched" {{$rec-> dispatch_status == 'Not yet dispatched' || $rec->dispatch_status == 'No'?'selected':''}}>Not Yet Dispatched</option>
                            </select>
                            @else
                            <label>Please Confirm This Order To Change Dispatch Status</label>
                            @endif
                            
                        </td>
                        <td style="text-align:center">
                            @if($rec->delivery_status)
                            {{$rec->delivery_status}}
                            @else
                            Not Delivered
                            @endif
                        </td>
						<!--<td style="text-align:center">-->
						    
						<!--    @if($rec->delivery_status == "Delivered")-->
						<!--    <a href="{{URL::to('/')}}/amprintLPO?id={{$rec->project_id}}&reqId={{ $rec->id }}" target="_blank" class="btn btn-sm btn-primary form-control" ><b>Print Invoice</b></a>-->
						<!--    @endif-->
						<!--</td>-->
						
						@if($rec->status === 'Order Placed')
					    <td style="text-align:center"><a onclick="confirmamOrder('{{$rec->id}}')" class="btn btn-sm btn-success" ><b>Confirm Order</b></a></td>
					    @elseif($rec->status === 'Order Initiated')
					    <td style="text-align:center">{{ $rec->status }}</td>
					    @elseif($rec->status === 'Order Cancelled')
					    <td style="text-align:center">{{ $rec->status }}</td>
					    @elseif($rec->delivery_status === 'Delivered')
					    <td style="text-align:center"><a href="{{URL::to('/')}}/amprintLPO?id={{$rec->project_id}}&reqId={{ $rec->id }}" target="_blank" class="btn btn-sm btn-primary form-control" ><b>Print Invoice</b></a></td>
					    @else
					        @if($rec->delivery_status !== 'Delivered')
					        <td style="text-align:center"><a onclick="cancelamOrder('{{$rec->id}}')" class="btn btn-sm btn-danger" style="width:99%" ><b>Cancel Order</b></a></td>
					        @else
					        <td>Order Delivered</td>
					        @endif
					    @endif
					    @endif
					    @if(Auth::user()->department_id == 1 && Auth::user()->group_id == 2)
					        @if($rec->status == "Order Initiated")
					        <td style="text-align:center"><a onclick="placeOrder('{{$rec->id}}')" class="btn btn-sm btn-success" style="width:99%" ><b>Place Order</b></a></td>
					        @else
					        <td style="text-align:center">{{ $rec->status }}</td>
					        @endif
					    @endif
					</tr>
					@endforeach
				</tbody>	
			</table>
			<br>
			<center>{{$view->links()}}</center>	
		</div>
	</div>
</div>
<div class='b'></div>
<div class='bb'></div>
<div class='message'>
  <div class='check'>
    &#10004;
  </div>
  <p>
    Success
  </p>
  <p>
    @if(session('Success'))
    {{ session('Success') }}
    @endif
  </p>
  <button id='ok'>
    OK
  </button>
</div>
<script src="http://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
	function filter()
	{
	    var date1 = document.getElementById('fromdate').value;
	    var date2 = document.getElementById('todate').value;
	    if(date2 < date1)
	    {
	        alert('To Date value should not be less than From Date !!!');
	        return false;
	    }
	    else
	    {
	        $.ajax({
	            type:'GET',
	            url: "{{URL::to('/')}}/filter",
	            data: {date1: date1, date2: date2},
	            async: false,
	            success: function(response)
	            {
	                document.getElementById('table').style.display = 'none';
	                var result = "<table class='table table-responsive table-striped' border='1' id='table'>";
	                result += "<thead><tr><th style='text-align:center'>Project ID</th><th style='text-align:center'></th></tr></thead>"
	                console.log(response);
	            }
	        });
	    }
	    return false;
	}
	function pay(arg)
	{
		var e = document.getElementById("selectPayment-"+arg);
		var strUser = e.options[e.selectedIndex].value;
		var ans = confirm('Are You Sure ?');
		if(ans){
			$.ajax({
				type: 'GET',
				url: "{{URL::to('/')}}/updatepay",
				data: {payment: strUser, id: arg},
				async: false,
				success: function(response){
					console.log(response);
				}
			});
		}
		return false;
	}
	function updateDispatch(arg)
	{
		var e = document.getElementById("selectdispatch-"+arg);
		var strUser = e.options[e.selectedIndex].value;
		var ans = confirm('Are You Sure ?');
		if(ans){
    		$.ajax({
    			type: 'GET',
    			url: "{{URL::to('/')}}/updatedispatch",
    			data: {dispatch: strUser, id: arg},
    			async: false,
    			success: function(response){
    				console.log(response);	
    			}
    		});
		}
		return false;	
	}
	
	
	function confirmamOrder(arg)
	{
	    var ans = confirm('Are You Sure To Confirm This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/confirmamOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }    
	}
	
	function cancelamOrder(arg)
	{
	    var ans = confirm('Are You Sure To Cancel This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/cancelamOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }
	 }
	 function placeOrder(arg)
	{
	    var ans = confirm('Are You Sure To Finally Place This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/placeOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }
	 }


</script>
@endsection